### ISSUE TITLE
Game of Fifteen

### ISSUE THREAD

**Issue by marwanbshara** [k3rnel-pan1c/CS50-Introduction-to-Computer-Science-SOLUTIONS#1]
Please help me with my code down over here : 
/**
 * fifteen.c
 *
 * Implements Game of Fifteen (generalized to d x d).
 *
 * Usage: fifteen d
 *
 * whereby the board's dimensions are to be d x d,
 * where d must be in [DIM_MIN,DIM_MAX]
 *
 * Note that usleep is obsolete, but it offers more granularity than
 * sleep and is simpler to use than nanosleep; `man usleep` for more.
 */

#define _XOPEN_SOURCE 500

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// constants
#define DIM_MIN 3
#define DIM_MAX 9

// board
int board[DIM_MAX][DIM_MAX];

// dimensions
int d;

// prototypes
void clear(void);
void greet(void);
void init(void);
void draw(void);
bool move(int tile);
bool won(void);
bool legalToMove(void);
void swapt(int Tilei, int Tilej, int blank_i, int blank_j);
void tilelocat(int);

int main(int argc, string argv[])
{
    // ensure proper usage
    if (argc != 2)
    {
        printf("Usage: fifteen d\n");
        return 1;
    }

    // ensure valid dimensions
    d = atoi(argv[1]);
    if (d < DIM_MIN || d > DIM_MAX)
    {
        printf("Board must be between %i x %i and %i x %i, inclusive.\n",
            DIM_MIN, DIM_MIN, DIM_MAX, DIM_MAX);
        return 2;
    }

    // open log
    FILE *file = fopen("log.txt", "w");
    if (file == NULL)
    {
        return 3;
    }

    // greet user with instructions
    greet();

    // initialize the board
    init();

    // accept moves until game is won
    while (true)
    {
        // clear the screen
        clear();

        // draw the current state of the board
        draw();

        // log the current state of the board (for testing)
        for (int i = 0; i < d; i++)
        {
            for (int j = 0; j < d; j++)
            {
                fprintf(file, "%i", board[i][j]);
                if (j < d - 1)
                {
                    fprintf(file, "|");
                }
            }
            fprintf(file, "\n");
        }
        fflush(file);

        // check for win
        if (won())
        {
            printf("ftw!\n");
            break;
        }

        // prompt for move
        printf("Tile to move: ");
        int tile = get_int();

        // quit if user inputs 0 (for testing)
        if (tile == 0)
        {
            break;
        }

        // log move (for testing)
        fprintf(file, "%i\n", tile);
        fflush(file);

        // move if possible, else report illegality
        if (!move(tile))
        {
            printf("\nIllegal move.\n");
            usleep(500000);
        }

        // sleep thread for animation's sake
        usleep(500000);
    }

    // close log
    fclose(file);

    // success
    return 0;
}

/**
 * Clears screen using ANSI escape sequences.
 */
void clear(void)
{
    printf("\033[2J");
    printf("\033[%d;%dH", 0, 0);
}

/**
 * Greets player.
 */
void greet(void)
{
    clear();
    printf("WELCOME TO GAME OF FIFTEEN\n");
    usleep(2000000);
}

/**
 * Initializes the game's board with tiles numbered 1 through d*d - 1
 * (i.e., fills 2D array with values but does not actually print them).
 */
void init(void)
{
    int i,j,blanki=0,blankj=0;
    int n=(d*d)-1;
    for(i=0; i<d; i++)
    {
        for(j=0; j<d; j++)
        {
         board[i][j]=n;
            n--;
        }
        printf("\n");
    }

    if (((d*d)-1) % 2 != 0){
        int temp=board[d-1][d-2];
        board[d-1][d-2]=board[d-1][d-3];
        board[d-1][d-3]=temp;
    }
    blanki=d-1;
    blankj=d-1;
}

/**
 * Prints the board in its current state.
 */
void draw(void)
{
    int i,j;
    for(i=0; i<d; i++){
        for(j=0; j<d; j++){
            if(board[i][j]==0){
                printf("%2i'95'", board[i][j]);
            }
            else{
            printf("%2i", board[i][j]);
            }
            }

        printf("\n");
    }
}

/**
 * If tile borders empty space, moves tile and returns true, else
 * returns false.
 */
bool move(int tile)
{
    int Num=0;
    Num=tile;
    if(Num<0 || Num>(d*d-1)){
        return false;
    }
    tilelocat(Num);
    if(legalToMove())
    {
        swapt(Tilei, Tilej, blank_i, blank_j);
        return true;
    }
    else {
        return false;
    }
    return false;
}

/**
 * Returns true if game is won (i.e., board is in winning configuration),
 * else false.
 */
bool won(void)
{
    int i,j;
    int C=1;
    for(i=0;i<d;i++){
        for(j=0;j<d;j++){
            if(i==(d-1)&&j==(d-1)){
                if(board[i][j]==0)
                return true;
            }
            if(board[i][j]!=C)
            return false;
            else {
                C=C+1;
            }
        }
    }
    if(C==(d*d-1))
    return true;
}

void tilelocat(int tilel)
{
    int i,j;
    int Num=0;
    Num=tilel;
    int Tilei=0,Tilej=0;
    for(i=0;i<d;i++)
    {
        for(j=0;j<d;j++)
        {
        if(board[i][j]==Num)
        {
        Tilei=i;
        Tilej=j;
            }
        }
    }
}

void swapt(int Tilei,int Tilej, int blank_i,int blank_j)
{
    int temp=board[Tilei][Tilej];
    board[Tilei][Tilej]=board[blank_i][blank_j];
    board[blank_i][blank_j]=temp;
}

bool legalToMove(void)
{
    if(Tilei>0 && board[Tilei-1][Tilej]==0){
        blank_i= Tilei-1;
        blank_j=Tilej;
        return true;
    }
    if(Tilei<d-1 && board[Tilei+1][Tilej]==0){
        blank_i= Tilei+1;
        blank_j=Tilej;
        return true;
    }
    if(Tilej>0 && board[Tilei][Tilej-1]==0){
        blank_i= Tilei;
        blank_j=Tilej-1;
        return true;
    }
    if(Tilej<d-1 && board[Tilei][Tilej+1]==0){
        blank_i= Tilei;
        blank_j=Tilej+1;
        return true;
    }
    return false;
}

**Comment by ahmedkrmn** [comment]
Please indent your code in "~~~c" and "~~~" to make it clearer.

**Comment by marwanbshara** [comment]
~~~c
/**
 * fifteen.c
 *
 * Implements Game of Fifteen (generalized to d x d).
 *
 * Usage: fifteen d
 *
 * whereby the board's dimensions are to be d x d,
 * where d must be in [DIM_MIN,DIM_MAX]
 *
 * Note that usleep is obsolete, but it offers more granularity than
 * sleep and is simpler to use than nanosleep; `man usleep` for more.
 */

#define _XOPEN_SOURCE 500

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// constants
#define DIM_MIN 3
#define DIM_MAX 9

// board
int board[DIM_MAX][DIM_MAX];

// dimensions
int d;

// prototypes
void clear(void);
void greet(void);
void init(void);
void draw(void);
bool move(int tile);
bool won(void);
bool legalToMove(void);
void swapt(int Tilei, int Tilej, int blank_i, int blank_j);
void tilelocat(int);

int main(int argc, string argv[])
{
    // ensure proper usage
    if (argc != 2)
    {
        printf("Usage: fifteen d\n");
        return 1;
    }

    // ensure valid dimensions
    d = atoi(argv[1]);
    if (d < DIM_MIN || d > DIM_MAX)
    {
        printf("Board must be between %i x %i and %i x %i, inclusive.\n",
            DIM_MIN, DIM_MIN, DIM_MAX, DIM_MAX);
        return 2;
    }

    // open log
    FILE *file = fopen("log.txt", "w");
    if (file == NULL)
    {
        return 3;
    }

    // greet user with instructions
    greet();

    // initialize the board
    init();

    // accept moves until game is won
    while (true)
    {
        // clear the screen
        clear();

        // draw the current state of the board
        draw();

        // log the current state of the board (for testing)
        for (int i = 0; i < d; i++)
        {
            for (int j = 0; j < d; j++)
            {
                fprintf(file, "%i", board[i][j]);
                if (j < d - 1)
                {
                    fprintf(file, "|");
                }
            }
            fprintf(file, "\n");
        }
        fflush(file);

        // check for win
        if (won())
        {
            printf("ftw!\n");
            break;
        }

        // prompt for move
        printf("Tile to move: ");
        int tile = get_int();

        // quit if user inputs 0 (for testing)
        if (tile == 0)
        {
            break;
        }

        // log move (for testing)
        fprintf(file, "%i\n", tile);
        fflush(file);

        // move if possible, else report illegality
        if (!move(tile))
        {
            printf("\nIllegal move.\n");
            usleep(500000);
        }

        // sleep thread for animation's sake
        usleep(500000);
    }

    // close log
    fclose(file);

    // success
    return 0;
}

/**
 * Clears screen using ANSI escape sequences.
 */
void clear(void)
{
    printf("\033[2J");
    printf("\033[%d;%dH", 0, 0);
}

/**
 * Greets player.
 */
void greet(void)
{
    clear();
    printf("WELCOME TO GAME OF FIFTEEN\n");
    usleep(2000000);
}

/**
 * Initializes the game's board with tiles numbered 1 through d*d - 1
 * (i.e., fills 2D array with values but does not actually print them).
 */
void init(void)
{
    int i,j,blanki=0,blankj=0;
    int n=(d*d)-1;
    for(i=0; i<d; i++)
    {
        for(j=0; j<d; j++)
        {
         board[i][j]=n;
            n--;
        }
        printf("\n");
    }

    if (((d*d)-1) % 2 != 0){
        int temp=board[d-1][d-2];
        board[d-1][d-2]=board[d-1][d-3];
        board[d-1][d-3]=temp;
    }
    blanki=d-1;
    blankj=d-1;
}

/**
 * Prints the board in its current state.
 */
void draw(void)
{
    int i,j;
    for(i=0; i<d; i++){
        for(j=0; j<d; j++){
            if(board[i][j]==0){
                printf("%2i'95'", board[i][j]);
            }
            else{
            printf("%2i", board[i][j]);
            }
            }

        printf("\n");
    }
}

/**
 * If tile borders empty space, moves tile and returns true, else
 * returns false.
 */
bool move(int tile)
{
    int Num=0;
    Num=tile;
    if(Num<0 || Num>(d*d-1)){
        return false;
    }
    tilelocat(Num);
    if(legalToMove())
    {
        swapt(Tilei, Tilej, blank_i, blank_j);
        return true;
    }
    else {
        return false;
    }
    return false;
}

/**
 * Returns true if game is won (i.e., board is in winning configuration),
 * else false.
 */
bool won(void)
{
    int i,j;
    int C=1;
    for(i=0;i<d;i++){
        for(j=0;j<d;j++){
            if(i==(d-1)&&j==(d-1)){
                if(board[i][j]==0)
                return true;
            }
            if(board[i][j]!=C)
            return false;
            else {
                C=C+1;
            }
        }
    }
    if(C==(d*d-1))
    return true;
}

void tilelocat(int tilel)
{
    int i,j;
    int Num=0;
    Num=tilel;
    int Tilei=0,Tilej=0;
    for(i=0;i<d;i++)
    {
        for(j=0;j<d;j++)
        {
        if(board[i][j]==Num)
        {
        Tilei=i;
        Tilej=j;
            }
        }
    }
}

void swapt(int Tilei,int Tilej, int blank_i,int blank_j)
{
    int temp=board[Tilei][Tilej];
    board[Tilei][Tilej]=board[blank_i][blank_j];
    board[blank_i][blank_j]=temp;
}

bool legalToMove(void)
{
    if(Tilei>0 && board[Tilei-1][Tilej]==0){
        blank_i= Tilei-1;
        blank_j=Tilej;
        return true;
    }
    if(Tilei<d-1 && board[Tilei+1][Tilej]==0){
        blank_i= Tilei+1;
        blank_j=Tilej;
        return true;
    }
    if(Tilej>0 && board[Tilei][Tilej-1]==0){
        blank_i= Tilei;
        blank_j=Tilej-1;
        return true;
    }
    if(Tilej<d-1 && board[Tilei][Tilej+1]==0){
        blank_i= Tilei;
        blank_j=Tilej+1;
        return true;
    }
    return false;
}
~~~

**Comment by ahmedkrmn** [comment]
@marwanbshara The main pitfall of your code was the scope of your in-function-declared variables.


If you check your implemtation, you will find that you are creating the varaibles `Tilei`, `Tilej`, `blank_i`and  `blank_j` locally and accessing them globally thus giving you compilation errors. To overcome this, you can declare all of you variables globally before main which automatically initiallizes all of them to 0.


 You also had an issue in your `init (void)` function where you used a `printf("\n)` after filling each row. This would be valid if you are printing your board and you want to add a new line between each row, but in our case we only needed to initialze the board so there's no need for priniting anything.
 
 
 Another issue was with your `draw(void)` function which had to do with the formatting of the output.
 
 I've modified all these issues in your code and here is a working version, if you are still having any questions don't hesitate to ask :
~~~c
/**
 * fifteen.c
 *
 * Implements Game of Fifteen (generalized to d x d).
 *
 * Usage: fifteen d
 *
 * whereby the board's dimensions are to be d x d,
 * where d must be in [DIM_MIN,DIM_MAX]
 *
 * Note that usleep is obsolete, but it offers more granularity than
 * sleep and is simpler to use than nanosleep; `man usleep` for more.
 */

#define _XOPEN_SOURCE 500

#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

// constants
#define DIM_MIN 3
#define DIM_MAX 9

// board
int board[DIM_MAX][DIM_MAX];

// dimensions
int d;

//Declare all the variables globally so they are accessable by all the functions
int Tilei,Tilej,blank_i,blank_j;

// prototypes
void clear(void);
void greet(void);
void init(void);
void draw(void);
bool move(int tile);
bool won(void);
bool legalToMove(void);
void swapt(int Tilei, int Tilej, int blank_i, int blank_j);
void tilelocat(int);

int main(int argc, string argv[])
{
    // ensure proper usage
    if (argc != 2)
    {
        printf("Usage: fifteen d\n");
        return 1;
    }

    // ensure valid dimensions
    d = atoi(argv[1]);
    if (d < DIM_MIN || d > DIM_MAX)
    {
        printf("Board must be between %i x %i and %i x %i, inclusive.\n",
            DIM_MIN, DIM_MIN, DIM_MAX, DIM_MAX);
        return 2;
    }

    // open log
    FILE *file = fopen("log.txt", "w");
    if (file == NULL)
    {
        return 3;
    }

    // greet user with instructions
    greet();

    // initialize the board
    init();

    // accept moves until game is won
    while (true)
    {
        // clear the screen
        clear();

        // draw the current state of the board
        draw();

        // log the current state of the board (for testing)
        for (int i = 0; i < d; i++)
        {
            for (int j = 0; j < d; j++)
            {
                fprintf(file, "%i", board[i][j]);
                if (j < d - 1)
                {
                    fprintf(file, "|");
                }
            }
            fprintf(file, "\n");
        }
        fflush(file);

        // check for win
        if (won())
        {
            printf("ftw!\n");
            break;
        }

        // prompt for move
        printf("Tile to move: ");
        int tile = get_int();

        // quit if user inputs 0 (for testing)
        if (tile == 0)
        {
            break;
        }

        // log move (for testing)
        fprintf(file, "%i\n", tile);
        fflush(file);

        // move if possible, else report illegality
        if (!move(tile))
        {
            printf("\nIllegal move.\n");
            usleep(500000);
        }

        // sleep thread for animation's sake
        usleep(500000);
    }

    // close log
    fclose(file);

    // success
    return 0;
}

/**
 * Clears screen using ANSI escape sequences.
 */
void clear(void)
{
    printf("\033[2J");
    printf("\033[%d;%dH", 0, 0);
}

/**
 * Greets player.
 */
void greet(void)
{
    clear();
    printf("WELCOME TO GAME OF FIFTEEN\n");
    usleep(2000000);
}

/**
 * Initializes the game's board with tiles numbered 1 through d*d - 1
 * (i.e., fills 2D array with values but does not actually print them).
 */

// No need for printing
void init(void)
{
    int i,j,blanki=0,blankj=0;
    int n=(d*d)-1;
    for(i=0; i<d; i++)
    {
        for(j=0; j<d; j++)
        {
         board[i][j]=n;
            n--;
        }
        //No need for printf because this is just a function that initialize the values
        // printf("\n");
    }

    if (((d*d)-1) % 2 != 0){
        int temp=board[d-1][d-2];
        board[d-1][d-2]=board[d-1][d-3];
        board[d-1][d-3]=temp;
    }
    blanki=d-1;
    blankj=d-1;
}

/**
 * Prints the board in its current state.
 */
void draw(void)
{
    int i,j;
    for(i=0; i<d; i++){
        for(j=0; j<d; j++){
            if(board[i][j]==0){
                printf("   ");
            }
            else{
            printf("%2i ", board[i][j]);
            }
            }

        printf("\n");
    }
}

/**
 * If tile borders empty space, moves tile and returns true, else
 * returns false.
 */
bool move(int tile)
{
    int Num=0;
    Num=tile;
    if(Num<0 || Num>(d*d-1)){
        return false;
    }
    tilelocat(Num);
    if(legalToMove())
    {
        swapt(Tilei, Tilej, blank_i, blank_j);
        return true;
    }
    else {
        return false;
    }
    return false;
}

/**
 * Returns true if game is won (i.e., board is in winning configuration),
 * else false.
 */

//No need for the commented if condition
bool won(void)
{
    int i,j;
    int C=1;
    for(i=0;i<d;i++){
        for(j=0;j<d;j++){
            if(i==(d-1)&&j==(d-1))
            {
                if(board[i][j]==0)
                return true;
            }
            if(board[i][j]!=C)
            return false;
            else {
                C=C+1;
            }
        }
    }
    //No need for this if condition
    //if(C==(d*d-1))
    return true;
}


void tilelocat(int tilel)
{
    int i,j;
    int Num=0;
    Num=tilel;
    for(i=0;i<d;i++)
    {
        for(j=0;j<d;j++)
        {
        if(board[i][j]==Num)
        {
        Tilei=i;
        Tilej=j;
            }
        }
    }
}

void swapt(int Tilei,int Tilej, int blank_i,int blank_j)
{
    int temp=board[Tilei][Tilej];
    board[Tilei][Tilej]=board[blank_i][blank_j];
    board[blank_i][blank_j]=temp;
}

bool legalToMove(void)
{
    if(Tilei>0 && board[Tilei-1][Tilej]==0){
        blank_i= Tilei-1;
        blank_j=Tilej;
        return true;
    }
    if(Tilei<d-1 && board[Tilei+1][Tilej]==0){
        blank_i= Tilei+1;
        blank_j=Tilej;
        return true;
    }
    if(Tilej>0 && board[Tilei][Tilej-1]==0){
        blank_i= Tilei;
        blank_j=Tilej-1;
        return true;
    }
    if(Tilej<d-1 && board[Tilei][Tilej+1]==0){
        blank_i= Tilei;
        blank_j=Tilej+1;
        return true;
    }
    return false;
}
~~~

**Comment by marwanbshara** [comment]
Thank you A lot my time is so limited since I'm full time student and employed and try to study by myself coding is tough 
but thanks a lot
